resume/urls.py
from django.urls import path

from . import views


app_name = 'resume'

urlpatterns = [
    path('list/', views.resume_list, name='list'),
    path('new', views.resume_form, name='form'),
    path('<int:id>/', views.resume_detail, name='detail')
]

resume/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.forms import ValidationError
from django.core.validators import RegexValidator
from django.shortcuts import resolve_url

import re

# v 0.1.0 (Wanted style)
class Resume(models.Model):
    # essential fields
    title = models.CharField(max_length=25)
    email = models.EmailField()
    phone_number = models.CharField(max_length=14, validators=[
        RegexValidator(r'^01[016789]-[2-9]\d{2,3}-\d{4}$', message='Enter a valid phone number'),
    ])
    about_me = models.TextField()
    # auto fields
    created_at = models.DateTimeField(auto_now_add=True)
    # Relational model: User
    User = get_user_model()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return resolve_url('resume:detail', self.id)

class Career(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)
    since = models.DateField()
    until = models.DateField(blank=True, null=True)
    currently_employed = models.BooleanField()
    company = models.CharField(max_length=50)
    position = models.CharField(max_length=50)
    achievement = models.TextField()
    
class Education(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)
    since = models.DateField()
    until = models.DateField(blank=True, null=True)
    currently_attending = models.BooleanField()
    school_name = models.CharField(max_length=50)
    major = models.CharField(max_length=50)
    research_content = models.TextField()

class Award(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)
    at = models.DateField()
    activity_name = models.CharField(max_length=50)
    detail = models.TextField()

class Link(models.Model):
    resume = models.OneToOneField(Resume, on_delete=models.CASCADE)
    github = models.CharField(max_length=50, blank=True) # id
    stackoverflow = models.URLField(blank=True, validators=[ # url 
        RegexValidator(r'^(https?:\/\/)?stackoverflow\.com\/users\/\d+\/\w+\/?$', 
            message='Stackoverflow link should be "https://stackoverflow.com/users/<your_id>/<username>/" format')
    ]) 
    linkedin = models.URLField(blank=True, validators=[ # url
        RegexValidator(r'^(https?:\/\/)?www\.linkedin\.com\/in\/\w+\/?$', 
            message='Linkedin link should be "https://www.linkedin.com/in/<your_id>/" format')
    ]) 
    facebook = models.CharField(max_length=50, blank=True) # id
    twitter = models.CharField(max_length=50, blank=True, validators=[
        RegexValidator(r'^[^@][a-zA-Z0-9_]+', message='Enter a valid twitter ID, except leading @')
        ]) # id (except @)
    google_plus = models.URLField(blank=True, validators=[
        RegexValidator(r'^(https?:\/\/)?plus\.google\.com\/w+\/?$', 
            message='Google+ link should be "https://plus.google.com/<your_id>/" format')
    ]) 
    blog = models.URLField(blank=True)

resume/forms.py
from django import forms
from django.utils import timezone
from django.forms import ValidationError

from .models import Resume, Career, Education, Award, Link


class ResumeForm(forms.ModelForm):
    class Meta:
        model = Resume
        fields = '__all__'
        exclude = ('user',)
        widgets = {
            'phone_number': forms.TextInput(attrs={
                'placeholder': 'Phone number ex) 010-0000-0000' 
            }),
            'about_me': forms.Textarea(attrs={
                'rows': 5,    
                'placeholder': 'Make your resume stand out with a simple self introduction. (3-5 lines recommended)',
            }),
        }


class CareerForm(forms.ModelForm):
    since = forms.DateField(input_formats=['%Y.%m'], widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': '0000.0',
    }))
    until = forms.DateField(input_formats=['%Y.%m'], required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': '0000.0',
    }))

    class Meta:
        model = Career
        fields = '__all__'
        exclude = ('resume',)
        widgets = {
            'company': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Company Name',
            }),
            'position': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Task/Position',
            }),
            'achievement': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Major Achievement',
                'rows': 3,
            }),
            'currently_employed': forms.CheckboxInput(attrs={
                'class': 'custom-control-input form-control float-left',
            }),
        }

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['currently_employed'] == True:
            cleaned_data['until'] = timezone.now().date()
        # Check since < until
        if cleaned_data['since'] >= cleaned_data['until']:
            raise ValidationError('"Until" should be later than "Since"')


class EducationForm(forms.ModelForm):
    since = forms.DateField(input_formats=['%Y.%m'], widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': '0000.0',
    }))
    until = forms.DateField(input_formats=['%Y.%m'], required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': '0000.0',
    }))
    class Meta:
        model = Education
        fields = '__all__'
        exclude = ('resume',)
        widgets = {
            'school_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'School Name',
            }),
            'major': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Major',
            }),
            'research_content': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Compeletion Courses or Research Content',
                'rows': 3,
            }),
            'currently_attending': forms.CheckboxInput(attrs={
                'class': 'custom-control-input form-control',
            }),
        }

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['currently_attending'] == True:
            cleaned_data['until'] = timezone.now().date()
        # Check since < until
        if cleaned_data['since'] >= cleaned_data['until']:
            raise ValidationError('"Until" should be later than "Since"')

class AwardForm(forms.ModelForm):
    at = forms.DateField(input_formats=['%Y.%m'], widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': '0000.0',
    }))
    class Meta:
        model = Award
        fields = '__all__'
        exclude = ('resume',)
        widgets = {
            'activity_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Activity Name',
            }),
            'detail': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Detail',
                'rows': 3,
            }),
        }

class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = '__all__'
        exclude = ('resume',)
        widgets = {
            'github': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Github ID',
            }),
            'stackoverflow': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Stackoverflow URL',
            }),
            'linkedin': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Linked URL',
            }),
            'facebook': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Facebook ID',
            }),
            'twitter': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Twitter ID(except @)',
            }),
            'google_plus': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Google+ URL',
            }),
            'blog': forms.URLInput(attrs={
                'class': 'form-control',
                'placeholder': 'Blog URL',
            })
        }

resume/views.py
from django.conf import settings
from django.forms.models import modelformset_factory
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.generic import DetailView

import pickle

from .forms import ResumeForm, CareerForm, EducationForm, AwardForm, LinkForm
from .models import Resume, Career, Education, Award, Link


def resume_detail(request, id):
    resume = get_object_or_404(Resume, id=id)
    if request.user != resume.user:
        return HttpResponse('No Permission')

    return render(request, 'resume/detail.html', {
        'resume': resume,
    })

def resume_form(request):
    # Prepare formsets
    CareerFormSet = modelformset_factory(Career, 
        form=CareerForm,
        max_num=5, 
        validate_max=True,
        extra=0
    )

    EducationFormSet = modelformset_factory(Education, 
        form=EducationForm,
        max_num=5, 
        validate_max=True,
        extra=0
    )

    AwardFormSet = modelformset_factory(Award, 
        form=AwardForm,
        max_num=5, 
        validate_max=True,
        extra=0
    )

    if request.method == 'POST':
        # Resume POST form
        form = ResumeForm(request.POST)

        # Career POST formset
        career_formset = CareerFormSet(request.POST, 
            prefix='career', 
            queryset=Career.objects.none()
        )

        # Education POST formset
        education_formset = EducationFormSet(request.POST, 
            prefix='education', 
            queryset=Education.objects.none()
        )
        
        # Award POST formset
        award_formset = AwardFormSet(request.POST,
            prefix='award',
            queryset=Award.objects.none()
        )
        
        # Link POST form
        link_form = LinkForm(request.POST)

        if form.is_valid() and career_formset.is_valid() and education_formset.is_valid() and award_formset.is_valid() and link_form.is_valid():
            # save Resume
            resume = form.save(commit=False)
            resume.user = request.user
            resume.save()

            # save Career
            careers = career_formset.save(commit=False)
            for career in careers:
                career.resume = resume
                career.save()

            # save Education 
            educations = education_formset.save(commit=False)
            for education in educations:
                education.resume = resume
                education.save()

            # save Award 
            awards = award_formset.save(commit=False)
            for award in awards:
                award.resume = resume
                award.save()

            # save Link
            link = link_form.save(commit=False)
            link.resume = resume
            link.save()

            return redirect('resume:list')
    else:
        # Resume GET form
        form = ResumeForm(initial={
            'email': request.user.email,
        })

        # Career GET form
        career_formset = CareerFormSet(prefix='career',
            queryset=Career.objects.none()
        )

        # Education GET form
        education_formset = EducationFormSet(prefix='education',
            queryset=Education.objects.none()
        )

        # Award GET form
        award_formset = AwardFormSet(prefix='award',
            queryset=Award.objects.none()
        )

        # Link GET form
        link_form = LinkForm()

    # Load devicon name list from the pickle file
    pkl_file = settings.ROOT('devfolio', 'static', 'devicon_name_list.pkl')
    with open(pkl_file, 'rb') as f:
        devicon_name_list = pickle.load(f)

    return render(request, 'resume/form.html', {
        'form': form,
        'career_formset': career_formset,
        'education_formset': education_formset,
        'award_formset': award_formset,
        'link_form': link_form,
        'first_row_field_list': ['until', 'since', 'at', 'currently_employed', 'currently_attending'],
        'date_field_list': ['until', 'since', 'at'],
        'devicon_name_list': devicon_name_list,
    })

def resume_list(request):
    resume_list = Resume.objects.filter(user=request.user.id)
    return render(request, 'resume/list.html', {
        'resume_list': resume_list,
    })

resume/templates/resume/award_formset.html
    <!-- AwardFormset Data -->
    {{ award_formset.management_form }}

    <!-- Award_Formset: Add button -->
    <a id="add-{{ award_formset.prefix }}" class="btn btn-default">
      <i class="fas fa-plus"></i>
      {# FIXME: using bootstrap class #}
      <span style="font-size: 2em;">{{ award_formset.prefix | title }}</span>
    </a>
 
    <!-- Award Formset -->
    <div class="{{ award_formset.prefix }}-formset">
    <!-- Award Formset: Non Form Errors -->
    {% for error in award_formset.non_form_errors %} 
      <p class="text-danger">
        {{ error }}
      </p>
    {% endfor %}
  
      {% for form in award_formset %}
      <!-- Award Forms -->
        <div class="text-secondary {{ award_formset.prefix }}-form">
          <!-- Award: Non field errors -->
          {% for error in form.non_field_errors %}
            <p class="text-danger">
              {{ error }}
            </p>
          {% endfor %}
  
          <!-- Award: Hidden Fields -->
          {% for field in form.hidden_fields %}
            {{ field }}
          {% endfor %}
  
          <!-- Award: Visible Fields -->
          
          <!-- Award: The First Row -->
          <div class="row">
            <div class="col-sm-10 order-sm-12">
              <!-- Empty Award: Close form button -->
              <a class="btn btn-default float-right close-{{ award_formset.prefix }}">
                <i class="fas fa-times"></i>
              </a>
            </div>
            {% for field in form.visible_fields %}
              
              {% if field.name in first_row_field_list %}
                {% if field.name in date_field_list %}
                <div class="col-sm-2">
                {% else %}
                {% endif %}
              
                <div class="form-group">
                
                  {{ field }}
                  
                  {% if field.errors %}
                    {% for error in field.errors %}
                      <p class="text-danger">
                        {{ error }}
                      </p>
                    {% endfor %}
                  {% endif %}
                
                </div>
              </div>
              {% endif %}
            {% endfor %}
          </div> <!-- Award: End of the First Row -->

          <!-- Award: The Other Rows -->
          <div class="row">
            {% for field in form.visible_fields %}

              {% if field.name not in first_row_field_list %}
              <div class="col-sm-12 mb-3">

                {{ field }}

              {% if field.errors %}
                {% for error in field.errors %}
                  <p class="text-danger">
                    {{ error }}
                  </p>
                {% endfor %}
              {% endif %}

              </div>
              {% endif %}

            {% endfor %}
          </div> <!-- Award: End of the Other Rows -->

        </div>
      {% endfor %}

    </div>
  
    <div class="empty-{{ award_formset.prefix }}-form" style="display: none">
      <div class="text-secondary {{ award_formset.prefix }}-form">
        {% with award_formset.empty_form as form %} 
 
          <!-- Empty Award: Non field errors -->
          {% for error in form.non_field_errors %}
            <p class="text-danger">
              {{ error }}
            </p>
          {% endfor %}

          <!-- Empty Award: Hidden Fields -->
          {% for field in form.hidden_fields %}
            {{ field }}
          {% endfor %}

          <!-- Empty Award: Visible Fields -->

          <!-- Empty Award: The First Row -->
          <div class="row">
            <div class="col-sm-10 order-sm-12">
              <!-- Empty Award: Close form button -->
              <a class="btn btn-default float-right close-{{ award_formset.prefix }}">
                <i class="fas fa-times"></i>
              </a>
            </div>
            {% for field in form.visible_fields %}
              
              {% if field.name in first_row_field_list %}
                {% if field.name in date_field_list %}
                <div class="col-sm-2">
                {% else %}
                {% endif %}
              
                <div class="form-group">
                
                  {{ field }}
                  
                  {% if field.errors %}
                    {% for error in field.errors %}
                      <p class="text-danger">
                        {{ error }}
                      </p>
                    {% endfor %}
                  {% endif %}
                
                </div>
              </div>
              {% endif %}
            {% endfor %}
          </div> <!-- Empty Award: End of the First Row -->

          <!-- Empty Award: The Other Rows -->
          <div class="row">
            {% for field in form.visible_fields %}

              {% if field.name not in first_row_field_list %}
              <div class="col-sm-12 mb-3">

                {{ field }}

              {% if field.errors %}
                {% for error in field.errors %}
                  <p class="text-danger">
                    {{ error }}
                  </p>
                {% endfor %}
              {% endif %}

              </div>
              {% endif %}

            {% endfor %}
          </div> <!-- Empty Award: End of the Other Rows -->

        {% endwith %}


      </div>
    </div>

resume/templates/resume/career_form.html
    <!-- CareerFormset Data -->
    {{ formset.management_form }}

    <!-- Add button -->
    <a id="add-{{ formset.prefix }}" class="btn btn-default">
      <i class="fas fa-plus"></i>
      {# FIXME: using bootstrap class #}
      <span style="font-size: 2em;">{{ formset.prefix | title }}</span>
    </a>
 
    <!-- Career Formset -->
    <div class="form-set">
    <!-- Career Formset: Non Form Errors -->
    {% for error in formset.non_form_errors %} 
      <p class="text-danger">
        {{ error }}
      </p>
    {% endfor %}
  
      {% for form in formset %}
      <!-- Career Forms -->
        <div class="text-secondary {{ formset.prefix }}-form">
          <!-- Non field errors -->
          {% for error in form.non_field_errors %}
            <p class="text-danger">
              {{ error }}
            </p>
          {% endfor %}
  
          <!-- Hidden Fields -->
          {% for field in form.hidden_fields %}
            {{ field }}
          {% endfor %}
  
          <!-- Visible Fields -->
          <div class="row">
            {% for field in form.visible_fields %}
               
              {% if field.name in date_field_list %}
              <div class="col-sm-2">
              {% else %}
              <div class="col-sm-8">
              {% endif %}

                <div class="form-group">

                {% if field.name == 'currently_employed' %}
                  <div class="custom-control custom-checkbox">
                {% endif %}

                  {{ field }}

                  {% if field.name == 'currently_employed' %}
                  <label class="custom-control-label" for="{{ field.auto_id }}">
                    {{ field.label }}
                  </label>
                  {% endif %}

                  {% if field.errors %}
                    {% for error in field.errors %}
                      <p class="text-danger">
                        {{ error }}
                      </p>
                    {% endfor %}
                  {% endif %}

                  {% if field.name == 'currently_employed' %}
                    </div>
                  {% endif %}

                </div>
              </div>
            {% endfor %}
          </div>

          <!-- Close form button -->
          <a class="btn btn-default close-{{ formset.prefix }} pull-right">
            <i class="fas fa-times"></i>
          </a>
        </div>
      {% endfor %}
    </div>
  
    <div class="empty-{{ formset.prefix }}-form" style="display: none">
      <div class="text-secondary {{ formset.prefix }}-form">
        {% with formset.empty_form as form %} 
 
          <!-- Non field errors -->
          {% for error in form.non_field_errors %}
            <p class="text-danger">
              {{ error }}
            </p>
          {% endfor %}

          <!-- Hidden Fields -->
          {% for field in form.hidden_fields %}
            {{ field }}
          {% endfor %}

          <!-- Visible Fields -->
          <div class="row">
            {% for field in form.visible_fields %}
              
              {% if field.name in date_field_list %}
              <div class="col-sm-2">
              {% else %}
              <div class="col-sm-8">
              {% endif %}
              
                <div class="form-group">
                
                {% if field.name == 'currently_employed' %}
                  <div class="custom-control custom-checkbox">
                {% endif %}
                
                  {{ field }}
                  
                  {% if field.name == 'currently_employed' %}
                  <label class="custom-control-label" for="{{ field.auto_id }}">
                    {{ field.label }}
                  </label>
                  {% endif %}
                  
                  {% if field.errors %}
                    {% for error in field.errors %}
                      <p class="text-danger">
                        {{ error }}
                      </p>
                    {% endfor %}
                  {% endif %}

                {% if field.name == 'currently_employed' %}
                  </div>
                {% endif %}
                
                </div>
              </div>
            {% endfor %}
          </div>
        {% endwith %}

        <!-- Close form button -->
        <a class="btn btn-default close-{{ formset.prefix }}">
          <i class="fas fa-times"></i>
        </a>

      </div>
    </div>

resume/templates/resume/control_award_formset.html
<script>
  // Add form
  $(document).on('click', '#add-{{ award_formset.prefix }}', function(e) {
    var $totalFormsVal = $('#id_{{ award_formset.prefix }}-TOTAL_FORMS').val();
    var $totalFormsNum = parseInt($totalFormsVal);
    if($totalFormsNum < {{ award_formset.max_num }}) {
      // Add from empty_form
      $('.{{ award_formset.prefix }}-formset').append($('.empty-{{ award_formset.prefix }}-form').html().replace(/__prefix__/g, $totalFormsVal));
      $('#id_{{ award_formset.prefix }}-TOTAL_FORMS').val($totalFormsNum+1);
    }
  });

  // Close form
  $(document).on('click', '.close-{{ award_formset.prefix }}', function(e) {
    var $totalFormsVal = $('#id_{{ award_formset.prefix }}-TOTAL_FORMS').val();
    var $totalFormsNum = parseInt($totalFormsVal);

    if($totalFormsNum > 0) {
      // Close the form
      $(this).closest('.{{ award_formset.prefix }}-form').remove();

      var ${{ award_formset.prefix }}Forms = $('.{{ award_formset.prefix }}-form');
      var ${{ award_formset.prefix }}FormsNum = ${{ award_formset.prefix }}Forms.length - 1; 

      $('#id_{{ award_formset.prefix }}-TOTAL_FORMS').val(${{ award_formset.prefix }}FormsNum); // exclude empty_form

      for(var i = 0; i < ${{ award_formset.prefix }}FormsNum; i++) {
        $(${{ award_formset.prefix }}Forms.get(i)).find('.form-control, label').each(function() {
          updateFormsIndex(this, '{{ award_formset.prefix }}', i)
        });
      }

      return false;
    }
  });
</script>

resume/templates/resume/control_career_formset.html
<script>
  // Add form
  $(document).on('click', '#add-{{ career_formset.prefix }}', function(e) {
    var $totalFormsVal = $('#id_{{ career_formset.prefix }}-TOTAL_FORMS').val();
    var $totalFormsNum = parseInt($totalFormsVal);
    if($totalFormsNum < {{ career_formset.max_num }}) {
      // Add from empty_form
      $('.{{ career_formset.prefix }}-formset').append($('.empty-{{ career_formset.prefix }}-form').html().replace(/__prefix__/g, $totalFormsVal));
      $('#id_{{ career_formset.prefix }}-TOTAL_FORMS').val($totalFormsNum+1);
    }
  });

  // Close form
  $(document).on('click', '.close-{{ career_formset.prefix }}', function(e) {
    var $totalFormsVal = $('#id_{{ career_formset.prefix }}-TOTAL_FORMS').val();
    var $totalFormsNum = parseInt($totalFormsVal);

    if($totalFormsNum > 0) {
      // Close the form
      $(this).closest('.{{ career_formset.prefix }}-form').remove();

      var ${{ career_formset.prefix }}Forms = $('.{{ career_formset.prefix }}-form');
      var ${{ career_formset.prefix }}FormsNum = ${{ career_formset.prefix }}Forms.length - 1; 

      $('#id_{{ career_formset.prefix }}-TOTAL_FORMS').val(${{ career_formset.prefix }}FormsNum); // exclude empty_form

      for(var i = 0; i < ${{ career_formset.prefix }}FormsNum; i++) {
        $(${{ career_formset.prefix }}Forms.get(i)).find('.form-control, label').each(function() {
          updateFormsIndex(this, '{{ career_formset.prefix }}', i)
        });
      }

      return false;
    }
  });
</script>

resume/templates/resume/detail.html
{% extends 'resume/layout.html' %}

{% block content %}
  <div class="jumbotron">
    <h1>{{ resume.title }}</h1>
    <p class="lead">{{ resume.about_me }}</p>
    <hr class="my-4"/>
    <p class="lead">{{ resume.phone_number }}<p>
    <p class="lead">{{ resume.email }}<p>
  </div>

  {% with resume.career_set.all as careers %}
    {% if careers %}
    <div class="jumbotron">
      <h2>Careers</h2>
      {% for career in careers %}
      <hr class="my-4"/>

      <div class="row">
        <div class="col-sm-3 order-sm-12">
          <p>
            <strong>
              {{ career.since }} -
              {{ career.until }}
            </strong>
          </p>
        </div>

        <div class="col-sm-9 order-sm-0">
          <h4>{{ career.company }}</h4>
          <p class="lead">{{ career.position }}</p>
          <p>{{ career.achievement | linebreaks }}</p>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  {% endwith %}

  {% with resume.education_set.all as educations %}
    {% if educations %}
    <div class="jumbotron">
      <h2>Educations</h2>

      {% for education in educations %}
      <hr class="my-4"/>

      <div class="row">
        <div class="col-sm-3 order-sm-12">
          <p>
            <strong>
              {{ education.since }} -
              {{ education.until }}
            </strong>
          </p>
        </div>

        <div class="col-sm-9 order-sm-0">
          <h4>{{ education.school_name }}</h4>
          <p class="lead">{{ education.major }}</p>
          <p>{{ education.research_content | linebreaks }}</p>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  {% endwith %}

  {% with resume.award_set.all as awards %}
    {% if awards %}
    <div class="jumbotron">
      <h2>Awards</h2>

      {% for award in awards %}
      <hr class="my-4"/>

      <div class="row">
        <div class="col-sm-3 order-sm-12">
          <p>
            <strong>{{ award.at }}</strong>
          </p>
        </div>

        <div class="col-sm-9 order-sm-0">
          <h4>{{ award.activity_name }}</h4>
          <p class="lead">{{ award.detail | linebreaks }}</p>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  {% endwith %}

  {% with resume.link as link %}
    <div class="jumbotron">
      <h1 class="display-4">Link</h1>

      {% if link.github != "" %}
      <a href="https://github.com/{{ link.github }}" class="btn btn-outline-secondary mr-3">
        <i class="fab fa-github" style="font-size: 3em;"></i>
      </a>
      {% endif %}

      {% if link.stackoverflow != "" %} 
      <a href="{{ link.stackoverflow }}" class="btn btn-outline-secondary mr-3">
        <i class="fab fa-stack-overflow" style="font-size: 3em;"></i>
      </a>
      {% endif %}

      {% if link.linkedin %}
      <a href="{{ link.linkedin }}" class="btn btn-outline-secondary mr-3">
        <i class="fab fa-linkedin" style="font-size: 3em;"></i>
      </a>
      {% endif %}

      {% if link.facebook %}
      <a href="https://facebook.com/{{ link.facebook }}" class="btn btn-outline-secondary mr-3">
        <i class="fab fa-facebook" style="font-size: 3em;"></i>
      </a>
      {% endif %}
      
      {% if link.twitter %}
      <a href="https://twitter.com/{{ link.twitter }}" class="btn btn-outline-secondary mr-3">
        <i class="fab fa-twitter" style="font-size: 3em;"></i>
      </a>
      {% endif %}
       
      {% if link.google_plus %}
      <a href="{{ link.google_plus }}" class="btn btn-outline-secondary mr-3">
        <i class="fab fa-google-plus" style="font-size: 3em;"></i>
      </a>
      {% endif %}


      {% if link.blog %}
      <a href="{{ link.blog }}" class="btn btn-outline-secondary mr-3">
        <i class="fas fa-rss" style="font-size: 3em;"></i>
      </a>
      {% endif %}
    </div>
  {% endwith %}
{% endblock %}

resume/templates/resume/list.html
{% extends 'resume/layout.html' %}

{% block content %}
  <div class="album py-5">
    
    <div class="row">

      <div class="col-md-4">
        <div class="card mb-4 box-shadow" style="height: 16rem;">
          <div class="card-head fa-4x text-center">
            <span class="fa-layers fa-fw">
              <a href="{% url 'resume:form'%}" class="text-secondary">
                <i class="fas fa-plus"></i>  
              </a>
            </span>
          </div>
          <div class="card-body text-center">
            <h5 class="card-title text-success">
              New Resume
            </h5>
          </div>
        </div>
      </div>
      
      {% for resume in resume_list %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow" style="height: 16rem;">
          <div class="card-head fa-4x text-center">
            <span class="fa-layers fa-fw">
              <i class="fas fa-file-alt"></i>  
            </span>
          </div>
          <div class="card-body text-center">
            <h5 class="card-title text-success">
              {{ resume.title }}  
            </h5>
            <p class="card-text text-default text-left">
              {{ resume.created_at | date:'Y.m.d' }}
            </p>
            <a class="btn btn-default float-right" href="">Edit</a>
            <a class="btn btn-default float-right" href="{% url 'resume:detail' resume.id %}">View</a>
          </div>
        </div>
      </div>
      {% endfor %}

    </div>

  </div>
{% endblock %}