devfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings


urlpatterns = [
    path('', lambda r: redirect('login')),

    path('admin/', admin.site.urls),
    path('resume/', include('resume.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

resume/urls.py
from django.urls import path

from . import views


app_name = 'resume'

urlpatterns = [
    path('list/', views.resume_list, name='list'),
    path('new', views.resume_form, name='form'),
    path('<int:id>/', views.resume_detail, name='detail')
]

devfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}Devfolio</title>

  <link rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Damion">
  <!-- 기본 부트스트랩 -->
  <!--
  <link rel="stylesheet" href="{% static 'bootstrap-4.0.0-dist/css/bootstrap.min.css' %}">
  -->
  <!-- 부트와치 테마 -->
  <link href="https://maxcdn.bootstrapcdn.com/bootswatch/4.0.0-beta.3/solar/bootstrap.min.css" rel="stylesheet" integrity="sha384-Jpv9vxZao0dlyvegpeTxSgc5cczNCOpcV5ihm8RQbrMo263QmC3Sf5HIMBfr+nqx" crossorigin="anonymous">
  <!-- 커스텀 스타일 -->
  <link rel="stylesheet" href="{% static 'custom/footer.css' %}">
  <link rel="stylesheet" href="{% static 'custom/navbar.css' %}">
  <link rel="stylesheet" href="{% static 'custom/logo.css' %}">
  <link id="favicon" rel="icon" type="image/png" sizes="32x32" href="{% static 'images/devfolio-favicon.png'%}">

  <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">

  <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

</head>

<body>
  {%if user.is_authenticated %}
  <!-- 내비바 -->
  <header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">
        <img src="{% static 'images/devfolio-nav-logo.png'%}" alt="logo" width=115px>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle btn btn-nav btn-outline-secondary my-2 my-sm-0" href="" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-archive"></i>  
                Resumes
              </a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="{% url 'resume:form' %}">
                <i class="fas fa-file-alt"></i>  
                New Resume
              </a>
              <a class="dropdown-item" href="{% url 'resume:list' %}">
                <i class="fas fa-th-list"></i>  
                Resume List
              </a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <a class="btn btn-nav btn-outline-secondary my-2 my-sm-0" href="#" role="button">
            <img width="25px" height="25px" src="{% url 'identicon' %}" alt="identicon.png"/>
            {{ user.first_name }} {{ user.last_name }}</a>
          <a class="btn btn-nav btn-outline-secondary my-2 my-sm-0" href="{% url 'logout' %}" role="button"><i class="fas fa-sign-out-alt"></i> Sign out</a>
        </form>
      </div>
    </nav>
  </header>
  {% endif %}

  <!-- 본문 -->
  <div class="container-fluid">
    {% block content %}
    {% endblock %}
  </div>

  <!-- 푸터 -->
  <footer>
    <div class="container">
      <p class="text-center">
        <small class="text-muted">For educational purpose crafted with ❤️ 
        by <a href="https://github.com/flavono123">flavono123</a>.
        </small>
      </p>
    </div>
  </footer>

  <!-- JS 로드 -->
  <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js" integrity="sha384-feJI7QwhOS+hwpX2zkaeJQjeiwlhOP+SdQDqhgvvo1DsjtiSQByFdThsxO669S2D" crossorigin="anonymous"></script>


  {% block script %}
  {% endblock %}
</body>
</html>